# Modulus operator_____________

#===================================================================#

# INT % INT.................
print(20 % 10)                              # 0

# INT % FLOAT.................
print(20 % 10.5)                            # 9.5

# INT % COMPLEX.................
print(20 % (5+2j))                          # TypeError

# INT % BOOL.................
print(20 % True)                            # 0

# INT % STRING.................
print(20 % "Python")                        # TypeError

# INT % LIST.................
print(20 % [10, 20])                        # TypeError

# INT % TUPLE.................
print(20 % (10, 20))                        # TypeError

# INT % SET.................
print(20 % {10, 20})                        # TypeError

# INT % DICTIONARY.................
print(20 % {"a": 10})                       # TypeError

#===================================================================#

# FLOAT % INT.................
print(20.5 % 10)                            # 0.5

# FLOAT % FLOAT.................
print(20.5 % 10.5)                          # 10.0

# FLOAT % COMPLEX.................
print(20.5 % (5+2j))                        # TypeError

# FLOAT % BOOL.................
print(20.5 % True)                          # 0.5

# FLOAT % STRING.................
print(20.5 % "Python")                      # TypeError

# FLOAT % LIST.................
print(20.5 % [10, 20])                      # TypeError

# FLOAT % TUPLE.................
print(20.5 % (10, 20))                      # TypeError

# FLOAT % SET.................
print(20.5 % {10, 20})                      # TypeError

# FLOAT % DICTIONARY.................
print(20.5 % {"a": 10})                     # TypeError

#===================================================================#

# COMPLEX % INT.................
print((20+5j) % 10)                         # TypeError

# COMPLEX % FLOAT.................
print((20+5j) % 10.5)                       # TypeError

# COMPLEX % COMPLEX.................
print((20+5j) % (5+2j))                     # TypeError

# COMPLEX % BOOL.................
print((20+5j) % True)                       # TypeError

# COMPLEX % STRING.................
print((20+5j) % "Python")                   # TypeError

# COMPLEX % LIST.................
print((20+5j) % [10, 20])                   # TypeError

# COMPLEX % TUPLE.................
print((20+5j) % (10, 20))                   # TypeError

# COMPLEX % SET.................
print((20+5j) % {10, 20})                   # TypeError

# COMPLEX % DICTIONARY.................
print((20+5j) % {"a": 10})                  # TypeError

#===================================================================#

# BOOL % INT.................
print(True % 10)                            # 1

# BOOL % FLOAT.................
print(True % 10.5)                          # 1.0

# BOOL % COMPLEX.................
print(True % (5+2j))                        # TypeError

# BOOL % BOOL.................
print(True % True)                          # 0

# BOOL % STRING.................
print(True % "Python")                      # TypeError

# BOOL % LIST.................
print(True % [10, 20])                      # TypeError

# BOOL % TUPLE.................
print(True % (10, 20))                      # TypeError

# BOOL % SET.................
print(True % {10, 20})                      # TypeError

# BOOL % DICTIONARY.................
print(True % {"a": 10})                     # TypeError

#===================================================================#

# STRING % INT.................
print("Hello" % 3)                          # TypeError

# STRING % FLOAT.................
print("Hello" % 10.5)                       # TypeError

# STRING % COMPLEX.................
print("Hello" % (5+2j))                     # TypeError

# STRING % BOOL.................
print("Hello" % True)                       # TypeError

# STRING % STRING.................
print("Hello" % "Python")                   # TypeError

# STRING % LIST.................
print("Hello" % [10, 20])                   # TypeError

# STRING % TUPLE.................
print("Hello" % (10, 20))                   # TypeError

# STRING % SET.................
print("Hello" % {10, 20})                   # TypeError

# STRING % DICTIONARY.................
print("Hello" % {"a": 10})                  # TypeError

#===================================================================#

# LIST % INT.................
print([10, 20] % 3)                         # TypeError

# LIST % FLOAT.................
print([10, 20] % 10.5)                      # TypeError

# LIST % COMPLEX.................
print([10, 20] % (5+2j))                    # TypeError

# LIST % BOOL.................
print([10, 20] % True)                      # TypeError

# LIST % STRING.................
print([10, 20] % "Hello")                   # TypeError

# LIST % LIST.................
print([10, 20] % [30, 40])                  # TypeError

# LIST % TUPLE.................
print([10, 20] % (30, 40))                  # TypeError

# LIST % SET.................
print([10, 20] % {30, 40})                  # TypeError

# LIST % DICTIONARY.................
print([10, 20] % {"a": 10})                 # TypeError

#===================================================================#

# TUPLE % INT.................
print((10, 20) % 3)                         # TypeError

# TUPLE % FLOAT.................
print((10, 20) % 10.5)                      # TypeError

# TUPLE % COMPLEX.................
print((10, 20) % (5+2j))                    # TypeError

# TUPLE % BOOL.................
print((10, 20) % True)                      # TypeError

# TUPLE % STRING.................
print((10, 20) % "Hello")                   # TypeError

# TUPLE % LIST.................
print((10, 20) % [30, 40])                  # TypeError

# TUPLE % TUPLE.................
print((10, 20) % (30, 40))                  # TypeError

# TUPLE % SET.................
print((10, 20) % {30, 40})                  # TypeError

# TUPLE % DICTIONARY.................
print((10, 20) % {"a": 10})                 # TypeError

#===================================================================#

# SET % INT.................
print({10, 20} % 10)                        # TypeError

# SET % FLOAT.................
print({10, 20} % 10.5)                      # TypeError

# SET % COMPLEX.................
print({10, 20} % (5+2j))                    # TypeError

# SET % BOOL.................
print({10, 20} % True)                      # TypeError

# SET % STRING.................
print({10, 20} % "Hello")                   # TypeError

# SET % LIST.................
print({10, 20} % [30, 40])                  # TypeError

# SET % TUPLE.................
print({10, 20} % (30, 40))                  # TypeError

# SET % SET.................
print({10, 20} % {30, 40})                  # TypeError

# SET % DICTIONARY.................
print({10, 20} % {"a": 10})                 # TypeError

#===================================================================#

# DICTIONARY % INT.................
print({"a": 10} % 10)                       # TypeError

# DICTIONARY % FLOAT.................
print({"a": 10} % 10.5)                     # TypeError

# DICTIONARY % COMPLEX.................
print({"a": 10} % (5+2j))                   # TypeError

# DICTIONARY % BOOL.................
print({"a": 10} % True)                     # TypeError

# DICTIONARY % STRING.................
print({"a": 10} % "Hello")                  # TypeError

# DICTIONARY % LIST.................
print({"a": 10} % [10, 20])                 # TypeError

# DICTIONARY % TUPLE.................
print({"a": 10} % (10, 20))                 # TypeError

# DICTIONARY % SET.................
print({"a": 10} % {10, 20})                 # TypeError

# DICTIONARY % DICTIONARY.................
print({"a": 10} % {"b": 20})                # TypeError

#===================================================================#