# Power / Exponentiation operator_____________

#===================================================================#

# INT ** INT.................
print(10 ** 2)                              # 100

# INT ** FLOAT.................
print(10 ** 2.5)                            # 316.22776601683796

# INT ** COMPLEX.................
print(10 ** (2+1j))                         # Complex result

# INT ** BOOL.................
print(10 ** True)                           # 10

# INT ** STRING.................
print(10 ** "Python")                       # TypeError

# INT ** LIST.................
print(10 ** [2, 3])                         # TypeError

# INT ** TUPLE.................
print(10 ** (2, 3))                         # TypeError

# INT ** SET.................
print(10 ** {2, 3})                         # TypeError

# INT ** DICTIONARY.................
print(10 ** {"a": 2})                       # TypeError

#===================================================================#

# FLOAT ** INT.................
print(10.5 ** 2)                            # 110.25

# FLOAT ** FLOAT.................
print(10.5 ** 2.0)                          # 110.25

# FLOAT ** COMPLEX.................
print(10.5 ** (2+1j))                       # Complex result

# FLOAT ** BOOL.................
print(10.5 ** True)                         # 10.5

# FLOAT ** STRING.................
print(10.5 ** "Python")                     # TypeError

# FLOAT ** LIST.................
print(10.5 ** [2, 3])                       # TypeError

# FLOAT ** TUPLE.................
print(10.5 ** (2, 3))                       # TypeError

# FLOAT ** SET.................
print(10.5 ** {2, 3})                       # TypeError

# FLOAT ** DICTIONARY.................
print(10.5 ** {"a": 2})                     # TypeError

#===================================================================#

# COMPLEX ** INT.................
print((2+3j) ** 2)                          # (-5+12j)

# COMPLEX ** FLOAT.................
print((2+3j) ** 2.0)                        # Complex result

# COMPLEX ** COMPLEX.................
print((2+3j) ** (1+1j))                     # Complex result

# COMPLEX ** BOOL.................
print((2+3j) ** True)                       # (2+3j)

# COMPLEX ** STRING.................
print((2+3j) ** "Python")                   # TypeError

# COMPLEX ** LIST.................
print((2+3j) ** [2, 3])                     # TypeError

# COMPLEX ** TUPLE.................
print((2+3j) ** (2, 3))                     # TypeError

# COMPLEX ** SET.................
print((2+3j) ** {2, 3})                     # TypeError

# COMPLEX ** DICTIONARY.................
print((2+3j) ** {"a": 2})                   # TypeError

#===================================================================#

# BOOL ** INT.................
print(True ** 2)                            # 1

# BOOL ** FLOAT.................
print(True ** 2.5)                          # 1.0

# BOOL ** COMPLEX.................
print(True ** (2+1j))                       # (1+0j)

# BOOL ** BOOL.................
print(True ** False)                        # 1

# BOOL ** STRING.................
print(True ** "Python")                     # TypeError

# BOOL ** LIST.................
print(True ** [2, 3])                       # TypeError

# BOOL ** TUPLE.................
print(True ** (2, 3))                       # TypeError

# BOOL ** SET.................
print(True ** {2, 3})                       # TypeError

# BOOL ** DICTIONARY.................
print(True ** {"a": 2})                     # TypeError

#===================================================================#

# STRING ** INT.................
print("Python" ** 2)                        # TypeError

# STRING ** FLOAT.................
print("Python" ** 2.5)                      # TypeError

# STRING ** COMPLEX.................
print("Python" ** (2+1j))                   # TypeError

# STRING ** BOOL.................
print("Python" ** True)                     # TypeError

# STRING ** STRING.................
print("Python" ** "Java")                   # TypeError

# STRING ** LIST.................
print("Python" ** [2, 3])                   # TypeError

# STRING ** TUPLE.................
print("Python" ** (2, 3))                   # TypeError

# STRING ** SET.................
print("Python" ** {2, 3})                   # TypeError

# STRING ** DICTIONARY.................
print("Python" ** {"a": 2})                 # TypeError

#===================================================================#

# LIST ** INT.................
print([10, 20] ** 2)                        # TypeError

# LIST ** FLOAT.................
print([10, 20] ** 2.5)                      # TypeError

# LIST ** COMPLEX.................
print([10, 20] ** (2+1j))                   # TypeError

# LIST ** BOOL.................
print([10, 20] ** True)                     # TypeError

# LIST ** STRING.................
print([10, 20] ** "Python")                 # TypeError

# LIST ** LIST.................
print([10, 20] ** [2, 3])                   # TypeError

# LIST ** TUPLE.................
print([10, 20] ** (2, 3))                   # TypeError

# LIST ** SET.................
print([10, 20] ** {2, 3})                   # TypeError

# LIST ** DICTIONARY.................
print([10, 20] ** {"a": 2})                 # TypeError

#===================================================================#

# TUPLE ** INT.................
print((10, 20) ** 2)                        # TypeError

# TUPLE ** FLOAT.................
print((10, 20) ** 2.5)                      # TypeError

# TUPLE ** COMPLEX.................
print((10, 20) ** (2+1j))                   # TypeError

# TUPLE ** BOOL.................
print((10, 20) ** True)                     # TypeError

# TUPLE ** STRING.................
print((10, 20) ** "Python")                 # TypeError

# TUPLE ** LIST.................
print((10, 20) ** [2, 3])                   # TypeError

# TUPLE ** TUPLE.................
print((10, 20) ** (2, 3))                   # TypeError

# TUPLE ** SET.................
print((10, 20) ** {2, 3})                   # TypeError

# TUPLE ** DICTIONARY.................
print((10, 20) ** {"a": 2})                 # TypeError

#===================================================================#

# SET ** INT.................
print({10, 20} ** 2)                        # TypeError

# SET ** FLOAT.................
print({10, 20} ** 2.5)                      # TypeError

# SET ** COMPLEX.................
print({10, 20} ** (2+1j))                   # TypeError

# SET ** BOOL.................
print({10, 20} ** True)                     # TypeError

# SET ** STRING.................
print({10, 20} ** "Python")                 # TypeError

# SET ** LIST.................
print({10, 20} ** [2, 3])                   # TypeError

# SET ** TUPLE.................
print({10, 20} ** (2, 3))                   # TypeError

# SET ** SET.................
print({10, 20} ** {2, 3})                   # TypeError

# SET ** DICTIONARY.................
print({10, 20} ** {"a": 2})                 # TypeError

#===================================================================#

# DICTIONARY ** INT.................
print({"a": 10} ** 2)                       # TypeError

# DICTIONARY ** FLOAT.................
print({"a": 10} ** 2.5)                     # TypeError

# DICTIONARY ** COMPLEX.................
print({"a": 10} ** (2+1j))                  # TypeError

# DICTIONARY ** BOOL.................
print({"a": 10} ** True)                    # TypeError

# DICTIONARY ** STRING.................
print({"a": 10} ** "Python")                # TypeError

# DICTIONARY ** LIST.................
print({"a": 10} ** [2, 3])                  # TypeError

# DICTIONARY ** TUPLE.................
print({"a": 10} ** (2, 3))                  # TypeError

# DICTIONARY ** SET.................
print({"a": 10} ** {2, 3})                  # TypeError

# DICTIONARY ** DICTIONARY.................
print({"a": 10} ** {"b": 2})                # TypeError

#===================================================================#